set(SDL_ROOT ${CMAKE_BINARY_DIR}/SDL)

if(TARGET_ANDROID OR TARGET_LINUX_GLES)
set(SDL_HIDAPI TRUE)
set(SDL_STATIC FALSE)
set(SDL_SHARED TRUE)
else()
set(SDL_HIDAPI TRUE)
set(SDL_STATIC TRUE)
set(SDL_SHARED FALSE)
endif()

# *Replicate* variables generated by `FindSDL`
set(SDL_FOUND TRUE)
set(SDL_INCLUDE_DIRS ${SDL_ROOT}/include/SDL2)
if(PLAT_MSVC)
    set(SDL_LIBRARIES ${SDL_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL2-static${CMAKE_STATIC_LIBRARY_SUFFIX})
else()
    if(SDL_SHARED)
        set(SDL_LIBRARIES ${SDL_ROOT}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}SDL2${CMAKE_SHARED_LIBRARY_SUFFIX})
    else()
        set(SDL_LIBRARIES ${SDL_ROOT}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SDL2${CMAKE_STATIC_LIBRARY_SUFFIX})
    endif()
endif()
set(SDL_VERSION 2.26.5)
string(REGEX MATCH "^[0-9]+" SDL_VERSION_MAJOR ${SDL_VERSION})
string(REGEX REPLACE "^[0-9]+\\.([0-9]+).*" "\\1" SDL_VERSION_MINOR ${SDL_VERSION})
string(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+).*" "\\1" SDL_VERSION_PATCH ${SDL_VERSION})
message(SDL_VERSION_MAJOR\ ==\ ${SDL_VERSION_MAJOR})
message(SDL_VERSION_MINOR\ ==\ ${SDL_VERSION_MINOR})
message(SDL_VERSION_PATCH\ ==\ ${SDL_VERSION_PATCH})

if(TARGET_LINUX_GLES)
    set(SDL_EXTRA_CMAKE_ARGS
        -DSDL_X11=OFF
        -DSDL_WAYLAND=OFF
        -DSDL_KMSDRM=ON
        -DSDL_OPENGLES=ON
        -DSDL_VIDEO_OPENGL=OFF
        -DSDL_PULSEAUDIO=OFF
        -DSDL_PIPEWIRE=OFF
        -DSDL_JACK=OFF
        -DSDL_SNDIO=OFF
        -DSDL_LIBSAMPLERATE=OFF
        -DSDL_ALSA=ON
        -DSDL_ALSA_SHARED=ON
        -DSDL_LIBUDEV=ON
    )
else()
    set(SDL_EXTRA_CMAKE_ARGS)
endif()

if(TARGET_LINUX_GLES)
    set(SDL_EP_CACHE_ARGS
        CMAKE_ARGS          --toolchain ${CMAKE_TOOLCHAIN_FILE}
                            --install-prefix ${SDL_ROOT}
                            -DCMAKE_INSTALL_LIBDIR=lib
                            -DCMAKE_BUILD_TYPE:STRING=Release
                            -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
                            -DSDL_SHARED:BOOL=${SDL_SHARED}
                            -DSDL_STATIC:BOOL=${SDL_STATIC}
                            -DSDL_TEST:BOOL=FALSE
                            -DSDL_HIDAPI:BOOL=${SDL_HIDAPI}
                            -DCMAKE_POLICY_VERSION_MINIMUM=3.5
                            -DCMAKE_INSTALL_LIBDIR=lib
                            ${SDL_EXTRA_CMAKE_ARGS}
        CMAKE_CACHE_ARGS    -DSDL_LIBSAMPLERATE:BOOL=OFF
                            -DSDL_LIBSAMPLERATE_SHARED:BOOL=OFF
    )
else()
    set(SDL_EP_CACHE_ARGS
        CMAKE_ARGS          --toolchain ${CMAKE_TOOLCHAIN_FILE}
                            --install-prefix ${SDL_ROOT}
                            -DCMAKE_INSTALL_LIBDIR=lib
                            -DCMAKE_BUILD_TYPE:STRING=Release
                            -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
                            -DSDL_SHARED:BOOL=${SDL_SHARED}
                            -DSDL_STATIC:BOOL=${SDL_STATIC}
                            -DSDL_TEST:BOOL=FALSE
                            -DSDL_HIDAPI:BOOL=${SDL_HIDAPI}
                            -DCMAKE_POLICY_VERSION_MINIMUM=3.5
                            -DCMAKE_INSTALL_LIBDIR=lib
    )
endif()

ExternalProject_Add(
    SDL
    SOURCE_DIR          ${CMAKE_SOURCE_DIR}/lib/SDL
    BINARY_DIR          ${SDL_ROOT}
    INSTALL_DIR         ${SDL_ROOT}
    UPDATE_DISCONNECTED TRUE
    ${SDL_EP_CACHE_ARGS}
    BUILD_BYPRODUCTS    ${SDL_LIBRARIES}
)

# *Replicate* SDL target
if(NOT TARGET SDL::SDL)
    if(TARGET_ANDROID OR TARGET_LINUX_GLES)
        add_library(SDL::SDL SHARED IMPORTED)
    else()
        add_library(SDL::SDL STATIC IMPORTED)
    endif()
endif()
add_dependencies(SDL::SDL SDL)
file(MAKE_DIRECTORY ${SDL_INCLUDE_DIRS})
set_target_properties(
    SDL::SDL PROPERTIES
    IMPORTED_LOCATION ${SDL_LIBRARIES}
    IMPORTED_IMPLIB ${SDL_LIBRARIES}
)
target_include_directories(SDL::SDL INTERFACE ${SDL_INCLUDE_DIRS})
target_link_directories(SDL::SDL INTERFACE ${SDL_ROOT}/lib)

set(SDL2_LIBRARY ${SDL_ROOT}/lib)
set(SDL2_INCLUDE_DIR ${SDL_INCLUDE_DIRS})

# TODO why doesn't this work?
#if(TARGET_MACOS)
#    set(SDL_MACOS_FRAMEWORKS "-framework CoreAudio -framework Cocoa")
#    target_link_libraries(SDL::SDL INTERFACE ${SDL_MACOS_FRAMEWORKS})
#endif()
